# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: dev

steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureDevTestLabARM'
      ScriptType: 'FilePath'
      ScriptPath: './arm-deploy.ps1'
      ScriptArguments: -projectName 'dtl-citizen' `
        -environment 'qa' `
        -location 'eastus'
      azurePowerShellVersion: 'LatestVersion'
