# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: prod

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'arm-rg-dtl-sc'
      subscriptionId: '3ab0f28a-f137-4e85-9c80-8169c20ab6ad'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'rg-dtl'
      location: 'East US 2'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/ArtiomLK/AzureDevTestLabARM/main/mainTemplate.json'
      csmParametersFileLink: 'https://raw.githubusercontent.com/ArtiomLK/AzureDevTestLabARM/main/mainParameters.json'
      deploymentMode: 'Incremental'
      deploymentName: 'DeployDevTestLabARM'
