# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: prod

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'arm-rg-dtl-sc'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az deployment group create -n rollout0 -g $(rgName) -f mainTemplate.json -p projectName=$(projectName) env=$(env)'
